### ISSUE TITLE
undefined reference to 'moodycamel::ConcurrentQueueDefaultTraits::MAX_SEMA_SPINS' with 790db30d

### ISSUE THREAD

**Issue by williamleong** [cameron314/concurrentqueue#208]
Thanks @cameron314 for working on the implementation of MAX_SEMA_SPINS!

Was pretty eager to try this out but I'm having some trouble compiling:
`blockingconcurrentqueue.h:59: error: undefined reference to 'moodycamel::ConcurrentQueueDefaultTraits::MAX_SEMA_SPINS'`

It compiles okay if I use the prior commit 7912b95d.

**Comment by cameron314** [comment]
Darn. I'll have a look. What compiler are you on? It works for me on VS2019.

**Comment by williamleong** [comment]
clang 6.0 on Ubuntu 18.04. Executing make in the build folder gives this:

```
test -d bin || mkdir bin
g++ -std=c++11 -Wall -pedantic-errors -Wpedantic -Wconversion -pthread  -g -O0    -fno-elide-constructors ../tests/common/simplethread.cpp ../tests/common/systemtime.cpp ../tests/unittests/unittests.cpp -o bin/unittests -lrt
/tmp/ccDpY6Ay.o: In function `moodycamel::BlockingConcurrentQueue<int, moodycamel::MallocTrackingTraits>::BlockingConcurrentQueue(unsigned long)':
/home/tsllwl/source/kerrigan/src/Kikkoman/libraries/concurrentqueue/build/../tests/unittests/../../blockingconcurrentqueue.h:59: undefined reference to `moodycamel::ConcurrentQueueDefaultTraits::MAX_SEMA_SPINS'
collect2: error: ld returned 1 exit status
makefile:33: recipe for target 'bin/unittests' failed
make: *** [bin/unittests] Error 1
```

**Comment by vy0b0x** [comment]
`git reset --hard 79cec4c` will works

**Comment by cameron314** [comment]
Fixed, thanks.

**Comment by jimages** [comment]
the compile error still exists in the newest commit.
```
error: no member named 'MAX_SEMA_SPINS' in 'moodycamel::ConcurrentQueueDefaultTraits'
             : inner(capacity), sema(create<LightweightSemaphore>(0, (int)Traits::MAX_SEMA_SPINS), &BlockingConcurrentQueue::template destroy<LightweightSemaphore>)
```
compiler is
```
clang version 9.0.1
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm@9/bin
Found CUDA installation: /Developer/NVIDIA/CUDA-10.1, version 10.1
```

**Comment by jimages** [comment]
OK, I forget to update the `concurrentqueue.h`.

**Comment by williamleong** [comment]
Works good for me, thanks @cameron314 !
